[package]
name = "otc_escrow"
type = "contract"
authors = ["Jack Gilcrest", "Harsh Bajpai"]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v1.2.1", directory = "noir-projects/aztec-nr/aztec" }
token_contract = { path = "../../deps/aztec-standards/src/token_contract" }
poseidon = { git = "https:/github.com/noir-lang/poseidon", tag = "v0.1.1" }